services:
  albyhub:
    # you can manually specify the platform if you use something other than linux/amd64,linux/arm64 e.g.
    #platform: linux/arm64/v8
    container_name: albyhub
    image: ghcr.io/getalby/hub:latest
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - LOG_EVENTS=true
      - MEMPOOL_API=https://mutinynet.com/api
      - LDK_NETWORK=signet
      - LDK_ESPLORA_SERVER=https://mutinynet.com/api
      - WORK_DIR=./data
